# This is an example Quickstarter pipeline yaml configuration
# Demonstrates multiple stages & parallel jobs execution

version: 1.0

stages:
  stage1:
    jobs:
    - [test1]
 

jobs:
  test1:
    type: custom-container
    parameters:
      image: ir.localzoho.com/alpine:latest
      scripts:
      - echo 'test'
    
      