- pipeline: "link"
  on: "SCHEDULE"
  start_date: "2024-04-01T08:25:00Z"
  delay: 5
  fail_on_prepare_env_warning: true
  actions:
  - action: "Wait for approval"
    type: "WAIT_FOR_APPLY"
    comment: "cm.ns.services@gmail.com"
  - action: "if ($BUDDY){echo \"yes\"}"
    type: "BUILD"
    docker_image_name: "library/ubuntu"
    docker_image_tag: "20.04"
    execute_commands:
    - "echo $BUDDY"
    - "echo $BUDDY_EXECUTION_CHANGELOG_ADDED"
    - "echo $BUDDY_EXECUTION_ID"
    - "echo $BUDDY_EXECUTION_BRANCH"
    - "echo $BUDDY_EXECUTION_MODE"
    shell: "BASH"
