# This is an example ant build template
# This pipeline clones the source repostiory & build ant application, then saves the artifacts

version: 1.0

stages:
  stage1:
    jobs:
    - [clonejob]
  

jobs:
  clonejob:
    description: repository cloning job
    type: source-checkout
    parameters:
      branch: main
